extends:
  - 'airbnb-base'

env:
  node: true
  es2020: true
  jest/globals: true

plugins:
  - jest

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]